"""empty message

Revision ID: ac7d276ba649
Revises: bb54c6c934b9
Create Date: 2025-05-10 17:16:00.885689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7d276ba649'
down_revision: Union[str, None] = 'bb54c6c934b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_attempts', sa.Column('type_test', sa.String(length=20), nullable=True))
    op.drop_constraint('user_attempts_user_id_test_id_key', 'user_attempts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_attempts_user_id_test_id_key', 'user_attempts', ['user_id', 'test_id'])
    op.drop_column('user_attempts', 'type_test')
    # ### end Alembic commands ###
