"""cases|delete cases topic

Revision ID: c11c7f65321a
Revises: afce5b782fd7
Create Date: 2025-06-08 21:29:26.955469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c11c7f65321a'
down_revision: Union[str, None] = 'afce5b782fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('section_topic_id', sa.Integer(), nullable=True))
    op.drop_index('ix_cases_section_cases_id', table_name='cases')
    op.create_index(op.f('ix_cases_section_topic_id'), 'cases', ['section_topic_id'], unique=False)
    op.create_foreign_key(None, 'cases', 'section_topic', ['section_topic_id'], ['id'])
    op.drop_column('cases', 'section_cases_id')
    op.add_column('section_topic', sa.Column('type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section_topic', 'type')
    op.add_column('cases', sa.Column('section_cases_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_index(op.f('ix_cases_section_topic_id'), table_name='cases')
    op.create_index('ix_cases_section_cases_id', 'cases', ['section_cases_id'], unique=False)
    op.drop_column('cases', 'section_topic_id')
    # ### end Alembic commands ###
