"""add column topic_id in cases

Revision ID: a90e26364ba0
Revises: e5e15fab6930
Create Date: 2025-06-15 18:45:36.168331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a90e26364ba0'
down_revision: Union[str, None] = 'e5e15fab6930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cases_topic_id'), 'cases', ['topic_id'], unique=False)
    op.create_foreign_key(None, 'cases', 'topics', ['topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_index(op.f('ix_cases_topic_id'), table_name='cases')
    op.drop_column('cases', 'topic_id')
    # ### end Alembic commands ###
