"""theo

Revision ID: fed60cea270c
Revises: c11c7f65321a
Create Date: 2025-06-10 21:50:55.054732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fed60cea270c'
down_revision: Union[str, None] = 'c11c7f65321a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_topic_id', sa.Integer(), nullable=False),
    sa.Column('book', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['section_topic_id'], ['section_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theories')
    # ### end Alembic commands ###
