"""empty message

Revision ID: 0297990480ee
Revises: ac7d276ba649
Create Date: 2025-05-10 17:20:29.935460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0297990480ee'
down_revision: Union[str, None] = 'ac7d276ba649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_attempts', ['user_id', 'test_id', 'type_test'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_attempts', type_='unique')
    # ### end Alembic commands ###
