"""last_update

Revision ID: c0a44ce8d0da
Revises: aa26a8dedf47
Create Date: 2025-04-21 21:01:57.802947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a44ce8d0da'
down_revision: Union[str, None] = 'aa26a8dedf47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tests_section_topic_id_fkey', 'tests', type_='foreignkey')
    op.create_foreign_key(None, 'tests', 'section_topic', ['section_topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_foreign_key('tests_section_topic_id_fkey', 'tests', 'topics', ['section_topic_id'], ['id'])
    # ### end Alembic commands ###
