"""last_update

Revision ID: aa26a8dedf47
Revises: 203f23f08097
Create Date: 2025-04-21 20:55:24.589818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa26a8dedf47'
down_revision: Union[str, None] = '203f23f08097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['sections_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_reward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['sections_topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'profiles', ['user_id'])
    op.add_column('tests', sa.Column('section_topic_id', sa.Integer(), nullable=False))
    op.drop_index('ix_tests_topic_id', table_name='tests')
    op.create_index(op.f('ix_tests_section_topic_id'), 'tests', ['section_topic_id'], unique=False)
    op.drop_constraint('tests_topic_id_fkey', 'tests', type_='foreignkey')
    op.create_foreign_key(None, 'tests', 'sections_topics', ['section_topic_id'], ['id'])
    op.drop_column('tests', 'topic_id')
    op.add_column('user_attempts', sa.Column('score', sa.Float(), nullable=False))
    op.drop_constraint('users_reward_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'reward_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reward_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_reward_id_fkey', 'users', 'rewards', ['reward_id'], ['id'])
    op.drop_column('user_attempts', 'score')
    op.add_column('tests', sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_foreign_key('tests_topic_id_fkey', 'tests', 'sections_topics', ['topic_id'], ['id'])
    op.drop_index(op.f('ix_tests_section_topic_id'), table_name='tests')
    op.create_index('ix_tests_topic_id', 'tests', ['topic_id'], unique=False)
    op.drop_column('tests', 'section_topic_id')
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_table('user_reward')
    op.drop_table('section_topic')
    # ### end Alembic commands ###
