"""updatelast|delete countq from user_attempts, img_url from topics

Revision ID: 5a2cfc96ebc8
Revises: 8d6a3f2cfa4b
Create Date: 2025-05-01 00:17:24.395036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a2cfc96ebc8'
down_revision: Union[str, None] = '8d6a3f2cfa4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section_topic', 'img_url')
    op.create_unique_constraint(None, 'user_attempts', ['user_id', 'test_id'])
    op.drop_column('user_attempts', 'total_questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_attempts', sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_attempts', type_='unique')
    op.add_column('section_topic', sa.Column('img_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
